development:
  adapter: postgresql
  encoding: unicode
  database: pngseqcompare_db
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 500

production:
  adapter: postgresql
  encoding: unicode
  database: pngseqcompare_db
  host: localhost
  port: 5432
  pool: 500